### ISSUE TITLE
Add agg/groupby command

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/xan#103]
- [x] Flag for when data is known to be sorted.
- [x] Parallelization
- [x] Figure out what to do with irrelevant/missing data/nulls. (Be consistent with stats). Notably, lex_first / lex_last etc.
- [x] count function should work like SQL wrt null values
- [x] add proper docs
- [x] mean/avg aliases
- [x] unit test variance related stuff
- [x] rename variance to var and force expression of population or sample variance (default being population)
- [ ] Kahan babushka sum
- [x] optimize sum by dynamic number assign
- [x] distinguish min/max by lexicographic order (& optimize min/max by cloning only if min = max)
- [x] -e option for dynamic evaluation group, allow full SelectColumns for the key?
- [x] need special error handling policies?
- [x] flag to give group column name

*Functions*

- [x] count
- [x] sum
- [x] all/any
- [x] mean
- [ ] unambiguous mode with fallback value
- [ ] geometric mean/harmonic mean
- [x] min
- [x] max
- [x] first (non null)
- [x] last (non null)
- [x] cardinality
- [ ] approx_cardinality
- [x] mode
- [x] median
- [x] variance
- [x] stdev
- [x] join/distinct
- [x] type
- [x] types
- [x] first lexical/last lexical
- [x] arg_min, arg_max, find

Refs:

- https://duckdb.org/docs/sql/aggregates.html
- https://www.sqlite.org/lang_aggfunc.html
- https://www.postgresql.org/docs/9.5/functions-aggregate.html

**Comment by AnnaCharles** [comment]
List of scenarios that the command should love :
1. Count the number of lines by group 
2. Count the mean of the number of lines by group 
3. Sum of the value of multiple columns by group
4. Sum of three different columns by group
5. mean of the value of a column by group 
6. maximum value of a column by group

**Comment by AnnaCharles** [comment]
List of the required aggregations :
- count
- sum 
- mean
- min
- max 
- cardinality 
- variance
- stdev
- median

**Comment by Yomguithereal** [comment]
First and last

**Comment by Yomguithereal** [comment]
I forgot to unit test variance related stuff

**Comment by Yomguithereal** [comment]
Need some argmax etc

**Comment by Yomguithereal** [comment]
Allowing to group on full selection implies to know how to output the result with multiple columns and rework --group-column.

**Comment by Yomguithereal** [comment]
We should filter null/nan etc invalid values and not panic. Add doc telling how to coalesce to handle nulls. 

Add separate fsum with kahan babuska. 

Create specific class using agg for stats without moonblade contamination.

**Comment by Yomguithereal** [comment]
Should the name of the column remains the one selected?
