### ISSUE TITLE
count agg function does not properly work with boolean values?

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/xan#217]

**Comment by bmaz** [comment]
xan groupby user_id 'count(retweeted_id ne "") as nb_original_tweets,count() as nb_tweets,count(retweeted_id eq "") as nb_rt,count(retweeted_id) as test' tweets_from_users_in_coherent_subevents_lola_from_monthly_export_2022-10_2022-11.csv.gz | xan view

```
┌────┬─────────────────────┬────────────────────┬───────────┬───────┬──────┐
│ -  │ user_id             │ nb_original_tweets │ nb_tweets │ nb_rt │ test │
├────┼─────────────────────┼────────────────────┼───────────┼───────┼──────┤
│ 0  │ 749972543579234304  │ 100                │ 100       │ 100   │ 19   │
│ 1  │ 1391981679238172673 │ 673                │ 673       │ 673   │ 613  │
│ 2  │ 1498956951388139524 │ 231                │ 231       │ 231   │ 126  │
│ 3  │ 937380062755741696  │ 1079               │ 1079      │ 1079  │ 893  │
│ 4  │ 1313413009264513029 │ 160                │ 160       │ 160   │ 4    │
│ 5  │ 50822235            │ 376                │ 376       │ 376   │ 241  │
│ 6  │ 118164746           │ 381                │ 381       │ 381   │ 358  │

```

**Comment by Yomguithereal** [comment]
So this is actually expected since count(true) or count(false) will still count something since it only ignores null values (i.e. `moonblade`'s `None` and empty strings). So `count(coalesce(retweeted_id ne ""))` would work or `count(if(retweeted_id ne "", true, "")` would also work. But none of those are actually very handy, so let's go with #216
