### ISSUE TITLE
xan merge should output path of wrong headers file

### ISSUE THREAD

**Issue by paulgirard** [medialab/xan#409]
Merge command fails when one CSV does not have same headers as the first one.
Which is great.
It would be useful to output which path created the error to help poor data scientists go correct their mess.

Error is thrown here :
https://github.com/medialab/xan/blob/master/src/cmd/merge.rs#L88

I am not a rust person but it would be doable to retrieve the bad CSV path by using the index in the iterator which has probably the same sequence than confs and paths.

**Comment by Yomguithereal** [comment]
@paulgirard the error will now show the first diverging file :) (released in v0.36.1).

Pro tip also: `xan headers *.csv` will show the diverging columns as being greyed out
