### ISSUE TITLE
xsv-medialab

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/xan#91]
Hello @BurntSushi, sorry to disturb you on a repo that is not yours but I felt you would not have liked to read this issue on [xsv](https://github.com/BurntSushi/xsv)'s repo directly.

SciencesPo's [médialab](https://medialab.sciencespo.fr/) has been thoroughly using your tool and we have maintained our fork for quite a time now and added/fixed a lot of things on our own version of your code. We of course understand and respect the fact that you did not want to merge some of the proposed additions upstream.

But now we feel that our version is sufficiently different from the original tool (all while retaining its skeleton and philosophy) and that we would like for people, including ourselves, to be able to install our version more easily than by asking `cargo` to install it through this forked GitHub repo. As such, we would like to publish a `xsv-medialab` crate that would install the command line binary still exposed as `xsv`.

Needless to say that your commits remain in our git tree and that your name as first author of the tool is still in the toml metadata of the package.

Would this be ok with you? Or do you think we should prefer: 1. keeping things the way they are today or 2. "rebrand" using a different name like `qsv` did.

Have a good day (or evening, or morning),

**Comment by BurntSushi** [comment]
Thanks! This sounds great. I do think it would be better to pick a different name though. At least a different binary name. But it's up to y'all. Thanks for carrying a version of the project forward. :-)

**Comment by Yomguithereal** [comment]
Thanks for your answer @BurntSushi. We will try to think of a different name then :)

**Comment by Yomguithereal** [comment]
@BurntSushi this fork has therefore been renamed to `xan` :)

I will now close this issue.
